#set_property PACKAGE_PIN AB25 [get_ports {IO_NAND_DQ[5]}]
#set_property PACKAGE_PIN AA25 [get_ports {IO_NAND_DQ[4]}]
#set_property PACKAGE_PIN W24 [get_ports {IO_NAND_DQ[3]}]
#set_property PACKAGE_PIN W23 [get_ports {IO_NAND_DQ[2]}]
#set_property PACKAGE_PIN AC21 [get_ports {IO_NAND_DQ[1]}]
#set_property PACKAGE_PIN AB21 [get_ports {IO_NAND_DQ[0]}]
#set_property PACKAGE_PIN AB22 [get_ports {IO_NAND_DQS_P[0]}]
#set_property PACKAGE_PIN V23 [get_ports {IO_NAND_DQ[6]}]
#set_property PACKAGE_PIN V24 [get_ports {IO_NAND_DQ[7]}]
#set_property SLEW FAST [get_ports {IO_NAND_DQ[7]}]
#set_property SLEW FAST [get_ports {IO_NAND_DQ[6]}]
#set_property SLEW FAST [get_ports {IO_NAND_DQ[5]}]
#set_property SLEW FAST [get_ports {IO_NAND_DQ[4]}]
#set_property SLEW FAST [get_ports {IO_NAND_DQ[3]}]
#set_property SLEW FAST [get_ports {IO_NAND_DQ[2]}]
#set_property SLEW FAST [get_ports {IO_NAND_DQ[1]}]
#set_property SLEW FAST [get_ports {IO_NAND_DQ[0]}]
#set_property DRIVE 8 [get_ports {IO_NAND_DQ[7]}]
#set_property DRIVE 8 [get_ports {IO_NAND_DQ[6]}]
#set_property DRIVE 8 [get_ports {IO_NAND_DQ[5]}]
#set_property DRIVE 8 [get_ports {IO_NAND_DQ[4]}]
#set_property DRIVE 8 [get_ports {IO_NAND_DQ[3]}]
#set_property DRIVE 8 [get_ports {IO_NAND_DQ[2]}]
#set_property DRIVE 8 [get_ports {IO_NAND_DQ[1]}]
#set_property DRIVE 8 [get_ports {IO_NAND_DQ[0]}]

#set_property PACKAGE_PIN AC24 [get_ports {O_NAND_WP_N[0]}]
#set_property PACKAGE_PIN AD24 [get_ports {O_NAND_WE_N[0]}]
#set_property PACKAGE_PIN T22 [get_ports {O_NAND_RE_P[0]}]
#set_property PACKAGE_PIN W25 [get_ports {O_NAND_CLE[0]}]
#set_property PACKAGE_PIN AD23 [get_ports {O_NAND_ALE[0]}]
#set_property PACKAGE_PIN G22 [get_ports sys_clk_50M]
#set_property PACKAGE_PIN D26 [get_ports sys_rst_n]



#set_property IOSTANDARD LVCMOS18 [get_ports sys_rst_n]
#set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_DQ[7]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_DQ[6]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_DQ[5]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_DQ[4]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_DQ[3]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_DQ[2]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_DQ[1]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_DQ[0]}]


#set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {IO_NAND_DQS_P[0]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_ALE[0]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CLE[0]}]
#set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {O_NAND_RE_P[0]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_WE_N[0]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_WP_N[0]}]
#set_property IOSTANDARD LVCMOS18 [get_ports sys_clk_50M]

#set_property PACKAGE_PIN J26 [get_ports nfc_start]
#set_property PACKAGE_PIN M21 [get_ports O_NAND_CE_N]
#set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CE_N[3]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CE_N[2]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CE_N[1]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CE_N[0]}]
#set_property IOSTANDARD LVCMOS18 [get_ports nfc_start]

#set_property PACKAGE_PIN M22 [get_ports I_NAND_RB_N]
#set_property IOSTANDARD LVCMOS18 [get_ports {I_NAND_RB_N[3]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {I_NAND_RB_N[2]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {I_NAND_RB_N[1]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {I_NAND_RB_N[0]}]

# NAND DQ 引脚绑定
set_property PACKAGE_PIN AB26 [get_ports {IO_NAND_DQ[5]}]
set_property PACKAGE_PIN AC26 [get_ports {IO_NAND_DQ[4]}]
set_property PACKAGE_PIN R26 [get_ports {IO_NAND_DQ[3]}]
set_property PACKAGE_PIN P26 [get_ports {IO_NAND_DQ[2]}]
set_property PACKAGE_PIN P19 [get_ports {IO_NAND_DQ[1]}]
set_property PACKAGE_PIN P20 [get_ports {IO_NAND_DQ[0]}]
set_property PACKAGE_PIN AE26 [get_ports {IO_NAND_DQ[6]}]
set_property PACKAGE_PIN AD26 [get_ports {IO_NAND_DQ[7]}]

# NAND DQS
set_property PACKAGE_PIN P24 [get_ports {IO_NAND_DQS_P[0]}]
set_property PACKAGE_PIN AB22 [get_ports {IO_NAND_DQS_N[0]}]

# 控制信号
set_property PACKAGE_PIN M25 [get_ports {O_NAND_WP_N[0]}]
set_property PACKAGE_PIN L24 [get_ports {O_NAND_WE_N[0]}]
set_property PACKAGE_PIN R16 [get_ports {O_NAND_RE_P[0]}]
set_property PACKAGE_PIN T20 [get_ports {O_NAND_CLE[0]}]
set_property PACKAGE_PIN R20 [get_ports {O_NAND_ALE[0]}]
set_property PACKAGE_PIN AF24 [get_ports O_NAND_CE_N]
set_property PACKAGE_PIN AF25 [get_ports I_NAND_RB_N]

# 时钟复位
set_property PACKAGE_PIN G22 [get_ports sys_clk_50M]
set_property PACKAGE_PIN D26 [get_ports sys_rst_n]

# 其他 IO
set_property PACKAGE_PIN J26  [get_ports nfc_start]
set_property PACKAGE_PIN B20 [get_ports uart_rxd]
set_property PACKAGE_PIN C22 [get_ports uart_txd]

# IOSTANDARD 设置
set_property IOSTANDARD LVCMOS18 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_DQ[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_DQ[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_DQ[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_DQ[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_DQ[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_DQ[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_DQ[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_NAND_DQ[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {IO_NAND_DQS_P[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {IO_NAND_DQS_N[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_ALE[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_CLE[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {O_NAND_RE_P[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_WE_N[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {O_NAND_WP_N[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports sys_clk_50M]
set_property IOSTANDARD LVCMOS18       [get_ports {O_NAND_CE_N[3]}]
set_property IOSTANDARD LVCMOS18       [get_ports {O_NAND_CE_N[2]}]
set_property IOSTANDARD LVCMOS18       [get_ports {O_NAND_CE_N[1]}]
set_property IOSTANDARD LVCMOS18       [get_ports {O_NAND_CE_N[0]}]
set_property IOSTANDARD LVCMOS18       [get_ports nfc_start]
set_property IOSTANDARD LVCMOS18       [get_ports {I_NAND_RB_N[3]}]
set_property IOSTANDARD LVCMOS18       [get_ports {I_NAND_RB_N[2]}]
set_property IOSTANDARD LVCMOS18       [get_ports {I_NAND_RB_N[1]}]
set_property IOSTANDARD LVCMOS18       [get_ports {I_NAND_RB_N[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS18 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS18 [get_ports I_NAND_RB_N]
set_property IOSTANDARD LVCMOS18 [get_ports O_NAND_CE_N]

# PULLUP
set_property PULLUP true [get_ports {I_NAND_RB_N[3]}]
set_property PULLUP true [get_ports {I_NAND_RB_N[2]}]
set_property PULLUP true [get_ports {I_NAND_RB_N[1]}]
set_property PULLUP true [get_ports {I_NAND_RB_N[0]}]
set_property PULLUP true [get_ports I_NAND_RB_N]

# SLEW 设置
set_property SLEW FAST [get_ports {IO_NAND_DQ[7]}]
set_property SLEW FAST [get_ports {IO_NAND_DQ[6]}]
set_property SLEW FAST [get_ports {IO_NAND_DQ[5]}]
set_property SLEW FAST [get_ports {IO_NAND_DQ[4]}]
set_property SLEW FAST [get_ports {IO_NAND_DQ[3]}]
set_property SLEW FAST [get_ports {IO_NAND_DQ[2]}]
set_property SLEW FAST [get_ports {IO_NAND_DQ[1]}]
set_property SLEW FAST [get_ports {IO_NAND_DQ[0]}]
set_property SLEW FAST [get_ports {IO_NAND_DQS_P[0]}]
set_property SLEW FAST [get_ports {IO_NAND_DQS_N[0]}]
set_property SLEW FAST [get_ports {O_NAND_ALE[0]}]
set_property SLEW FAST [get_ports {O_NAND_CLE[0]}]
set_property SLEW FAST [get_ports {O_NAND_RE_P[0]}]
set_property SLEW FAST [get_ports {O_NAND_RE_N[0]}]
set_property SLEW FAST [get_ports {O_NAND_WE_N[0]}]
set_property SLEW FAST [get_ports {O_NAND_WP_N[0]}]
set_property SLEW FAST [get_ports O_NAND_CE_N]
set_property SLEW FAST [get_ports uart_txd]

# DRIVE 强度
set_property DRIVE 8 [get_ports {IO_NAND_DQ[7]}]
set_property DRIVE 8 [get_ports {IO_NAND_DQ[6]}]
set_property DRIVE 8 [get_ports {IO_NAND_DQ[5]}]
set_property DRIVE 8 [get_ports {IO_NAND_DQ[4]}]
set_property DRIVE 8 [get_ports {IO_NAND_DQ[3]}]
set_property DRIVE 8 [get_ports {IO_NAND_DQ[2]}]
set_property DRIVE 8 [get_ports {IO_NAND_DQ[1]}]
set_property DRIVE 8 [get_ports {IO_NAND_DQ[0]}]
